# Generated by Django 5.1.4 on 2025-01-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_session_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("CANCELED", "Canceled"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
