# Generated by Django 5.1.4 on 2025-01-05 11:51

from django.db import migrations, models

import books_service.models


class Migration(migrations.Migration):

    dependencies = [
        ("books_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(
                null=True, upload_to=books_service.models.movie_image_file_path
            ),
        ),
    ]
