name: CI
on:
  pull_request:
    branches:
      - "dev"
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.12.6
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.6
      - name: Install Poetry and dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
          NGROK_HOST: ${{ secrets.NGROK_HOST }}
          TG_ADMIN_CHAT: ${{ secrets.TG_ADMIN_CHAT }}
          REDIS_HOST: redis
          REDIS_PORT: 6379
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}


      - name: Run migrations
        run: poetry run python manage.py migrate
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
          NGROK_HOST: ${{ secrets.NGROK_HOST }}
          TG_ADMIN_CHAT: ${{ secrets.TG_ADMIN_CHAT }}
          REDIS_HOST: redis
          REDIS_PORT: 6379
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}


      - name: Run tests
        run: poetry run python manage.py test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
          NGROK_HOST: ${{ secrets.NGROK_HOST }}
          TG_ADMIN_CHAT: ${{ secrets.TG_ADMIN_CHAT }}
          REDIS_HOST: redis
          REDIS_PORT: 6379
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
